spring.datasource.url=jdbc:postgresql://meubanco.com:5432/proddb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=produser
spring.datasource.password=prodpass
spring.jpa.hibernate.ddl-auto=validate
