CREATE TABLE USERS(
    id BIGSERIAL PRIMARY KEY,
    public_id BIGINT UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(150) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    role VARCHAR(10) NOT NULL DEFAULT 'USER',
    CONSTRAINT UK_EMAIL UNIQUE (email),
    CONSTRAINT role_check CHECK (role IN ('MANAGER', 'USER'))
);