CREATE TABLE USER_FAVORITES (
    user_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, book_id),
    FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE,
    FOREIGN KEY (book_id) REFERENCES BOOKS(id) ON DELETE CASCADE
);
