CREATE TABLE BOOK_RATINGS (
    id BIGSERIAL PRIMARY KEY,
    book_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    rating INT CHECK (rating BETWEEN 1 AND 5) NOT NULL,
    rated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_BOOK FOREIGN KEY (book_id) REFERENCES BOOKS(id) ON DELETE CASCADE,
    CONSTRAINT FK_USER FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE,
    CONSTRAINT UK_BOOK_USER UNIQUE (book_id, user_id)
);
